#!/bin/bash
echo "+-----------------------------------------------------------------------------+"
pid=`nvidia-smi | grep '|[^|]*[0-9][^|]*C[^|]*MiB[^|]*|' | awk '{print $2" "$3" "$5" "$6}'`
num=`echo $pid |wc|awk '{print $2}'`
range=$[$num/4]
for x in $(seq 0 $range);do
    echo $pid | awk '{print $(expr ($x*4+1))}'
done
# echo $pid | awk '{print $1 $2 $3 $4}' 
echo "+-----------------------------------------------------------------------------+"
